# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  build:
    docker:
      - image: brutalsimplicity/docker-with-buildx:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

workflows:
  build:
    jobs:
      - build:
          context: cloud-magix