service: serverless-dev-container

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
    
plugins:
  - serverless-webpack
    
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude: ['aws-sdk']
    keepOutputDirectory: true

functions:
  helloWorld:
    handler: src/entrypoint.handler
    events:
      - httpApi:
          path: /
          method: get
